

// SPDX-License-Identifier: MIT OR Apache-2.0

pragma solidity ^0.8.0;

import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";

import "./mixins/roles/AdminRole.sol";
import "./mixins/CollateralManagement.sol";
import "./mixins/WithdrawFromEscrow.sol";

/**
 * @notice The ABCpro treasury which collects fees generated by the market.
 * @dev The core responsibility of this contract is collecting fees.
 */
contract ABCTreasury is AdminRole, CollateralManagement, WithdrawFromEscrow {
  function initialize(address admin) public initializer {
    AdminRole._initializeAdminRole(admin);
  }
}